In [3]:
import numpy as np

In [4]:
arr = np.array([[[1.0e+03, 1.0e+03, 0.0e+00, 1.0e+03, 1.0e+03],
                    [4.3e-01, 4.3e-01, 4.3e-01, 0.0e+00, 4.3e-01],
                    [0.0e+00, 2.9e-01, 2.9e-01, 2.9e-01, 0.0e+00]],

                [[4.3e-01, 4.3e-01, 0.0e+00, 4.3e-01, 4.3e-01],
                    [1.0e+03, 1.0e+03, 1.0e+03, 0.0e+00, 1.0e+03],
                    [0.0e+00, 3.3e-01, 3.3e-01, 3.3e-01, 0.0e+00]],

                [[2.9e-01, 2.9e-01, 0.0e+00, 2.9e-01, 2.9e-01],
                    [3.3e-01, 3.3e-01, 3.3e-01, 0.0e+00, 3.3e-01],
                    [0.0e+00, 1.0e+03, 1.0e+03, 1.0e+03, 0.0e+00]]])

print(arr.shape)

(3, 3, 5)


Explain the following:
1. Sum of `arr` by axis = 0
2. Sum of `arr` by axis = 1
3. Sum of `arr` by axis = 2

In [5]:
print(np.sum(arr, axis=0).shape)
np.sum(arr, axis=0)

(3, 5)


array([[1000.72, 1000.72,    0.  , 1000.72, 1000.72],
       [1000.76, 1000.76, 1000.76,    0.  , 1000.76],
       [   0.  , 1000.62, 1000.62, 1000.62,    0.  ]])

In [6]:
print(np.sum(arr, axis=1).shape)
np.sum(arr, axis=1)

(3, 5)


array([[1.00043e+03, 1.00072e+03, 7.20000e-01, 1.00029e+03, 1.00043e+03],
       [1.00043e+03, 1.00076e+03, 1.00033e+03, 7.60000e-01, 1.00043e+03],
       [6.20000e-01, 1.00062e+03, 1.00033e+03, 1.00029e+03, 6.20000e-01]])

In [7]:
print(np.sum(arr, axis=2).shape)
np.sum(arr, axis=2)

(3, 3)


array([[4.00e+03, 1.72e+00, 8.70e-01],
       [1.72e+00, 4.00e+03, 9.90e-01],
       [1.16e+00, 1.32e+00, 3.00e+03]])